### ISSUE TITLE
Did the JSON endpoint change?

### ISSUE THREAD

**Issue by palewire** [trickvi/economics#2]
Getting this error when I try to init the Inflation object.

```DataPackageException: Unable to parse JSON at "http://data.okfn.org/data/cpi/". No JSON object could be decoded
```

Visiting the website, I see that the JSON is now here:

http://data.okfn.org/data/core/cpi/r/cpi.json

**Comment by cqkh42** [comment]
I've also noticed the endpoint only goes to 2014. Is there a new datasource? It is possible to use the world bank potentially

**Comment by trickvi** [comment]
Fixed by @cqkh42
